apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  DATABASE_USERNAME: cG9zdGdyZXM= # postgres (base64 encoded)
  DATABASE_PASSWORD: cGFzc3dvcmQ= # password (base64 encoded)
